// SPDX-License-Identifier: Apache-2.0
pragma solidity ^0.8.13;


import { Test } from "forge-std/Test.sol";

import { Fixed6, Fixed6Lib } from "../../src/number/types/Fixed6.sol";
import { UFixed6, UFixed6Lib } from "../../src/number/types/UFixed6.sol";
import { Fixed18, Fixed18Lib } from "../../src/number/types/Fixed18.sol";
import { UFixed18, UFixed18Lib } from "../../src/number/types/UFixed18.sol";

// solhint-disable no-console
import { console } from "../../src/utils/console.sol";

contract ConsoleTest is Test {
    uint256 constant MAX_UFIXED6 = type(uint256).max / 1e6;
    uint256 constant MAX_UFIXED18 = type(uint256).max / 1e18;
    int256 constant MIN_FIXED6 = type(int256).min / 1e6;
    int256 constant MAX_FIXED6 = type(int256).max / 1e6;
    int256 constant MIN_FIXED18 = type(int256).min / 1e18;
    int256 constant MAX_FIXED18 = type(int256).max / 1e18;

    function test_singleValues(uint256 unsigned, int256 signed) external view {
        console.log("foo");
        console.log(unsigned);
        console.log(signed);

        console.log(UFixed6Lib.from(bound(unsigned, 0, MAX_UFIXED6)));
        console.log(UFixed18Lib.from(bound(unsigned, 0, MAX_UFIXED18)));
        console.log(Fixed6Lib.from(bound(signed, MIN_FIXED6, MAX_FIXED6)));
        console.log(Fixed18Lib.from(bound(signed, MIN_FIXED18, MAX_FIXED18)));

        console.log(address(this));
        console.log(true);
        console.log(false);
    }

    function test_formatNonNumericValues(address a) external pure {
        console.log("      Address %s", a);
        console.log("      Bool %s ", uint160(a) / 2 < type(uint160).max / 2);
        console.log("      Bool %s (should be true) and %s (should be false)", true, false);
    }

    function test_formatInt(uint256 unsigned, int256 signed) external pure {
        console.log("      Unsigned int %s with trailing text", unsigned);
        console.log("      Signed int %s with trailing text", signed);
    }

    function test_formatFixed(uint256 u, int256 i) external pure {
        UFixed6 u6 = UFixed6Lib.from(bound(u, 0, MAX_UFIXED6));
        UFixed18 u18 = UFixed18Lib.from(bound(u, 0, MAX_UFIXED18));
        Fixed6 f6 = Fixed6Lib.from(bound(i, MIN_FIXED6, MAX_FIXED6));
        Fixed18 f18 = Fixed18Lib.from(bound(i, MIN_FIXED18, MAX_FIXED18));
        console.log("           Six decimal fixed %s (unsigned)", u6);
        console.log("      Eighteen decimal fixed %s (unsigned)", u18);
        console.log("           Six decimal fixed %s (signed)", f6);
        console.log("      Eighteen decimal fixed %s (signed)", f18);
    }

    function test_formatTwoInts(uint256 val1, uint256 val2) external pure {
        val1 = bound(val1, 0, uint256(type(int256).max));
        val2 = bound(val2, 0, uint256(type(int256).max));
        console.log("      Both unsigned and unsigned: %s and %s", uint(val1), uint(val2));
        console.log("      Both unsigned and signed:   %s and %s", uint(val1), int(val2)*-1);
        console.log("      Both signed and unsigned:   %s and %s", int(val1)*-1, uint(val2));
        console.log("      Both signed (negative):     %s and %s", int(val1)*-1, int(val2)*-1);
        console.log("      Both signed (positive):     %s and %s", int(val1), int(val2));
    }

    function test_formatTwoFixedValues(uint256 unsigned, int256 signed) external pure {
        UFixed6 uf6 = UFixed6Lib.from(bound(unsigned, 0, MAX_UFIXED6));
        UFixed18 uf18 = UFixed18Lib.from(bound(unsigned, 0, MAX_UFIXED18));
        Fixed6 f6 = Fixed6Lib.from(bound(signed, MIN_FIXED6, MAX_FIXED6));
        Fixed18 f18 = Fixed18Lib.from(bound(signed, MIN_FIXED18, MAX_FIXED18));
        console.log("      UFixed6 %s and UFixed6 %s", uf6, uf6);
        console.log("      UFixed18 %s and UFixed18 %s", uf18, uf18);
        console.log("      Fixed6 %s and Fixed6 %s", f6, f6);
        console.log("      Fixed18 %s and Fixed18 %s", f18, f18);
        console.log("      UFixed6 %s and UFixed18 %s", uf6, uf18);
        console.log("      Fixed6 %s and Fixed18 %s", f6, f18);
        console.log("      UFixed6 %s and Fixed18 %s", uf6, f18);
        console.log("      Fixed6 %s and UFixed18 %s", f6, uf18);
        console.log("      UFixed6 %s and Fixed6 %s", uf6, f6);
        console.log("      UFixed18 %s and Fixed18 %s", uf18, f18);
        console.log("      Fixed6 %s and UFixed6 %s", f6, uf6);
        console.log("      Fixed18 %s and UFixed18 %s", f18, uf18);
    }

    function test_formatTwoValues(uint256 u, int256 i, address a, bool b) external pure {
        UFixed6 uf6 = UFixed6Lib.from(bound(u, 0, MAX_UFIXED6));
        UFixed18 uf18 = UFixed18Lib.from(bound(u, 0, MAX_UFIXED18));
        Fixed6 f6 = Fixed6Lib.from(bound(i, MIN_FIXED6, MAX_FIXED6));
        Fixed18 f18 = Fixed18Lib.from(bound(i, MIN_FIXED18, MAX_FIXED18));
        console.log("      uint256 %s and uint256 %s", u, u);
        console.log("      uint256 %s and int256 %s", u, i);
        console.log("      uint256 %s and address %s", u, a);
        console.log("      uint256 %s and bool %s", u, b);
        console.log("      uint256 %s and UFixed6 %s", u, uf6);
        console.log("      uint256 %s and UFixed18 %s", u, uf18);
        console.log("      uint256 %s and Fixed6 %s", u, f6);
        console.log("      uint256 %s and Fixed18 %s", u, f18);
        console.log("      int256 %s and uint256 %s", i, u);
        console.log("      int256 %s and int256 %s", i, i);
        console.log("      int256 %s and address %s", i, a);
        console.log("      int256 %s and bool %s", i, b);
        console.log("      int256 %s and UFixed6 %s", i, uf6);
        console.log("      int256 %s and UFixed18 %s", i, uf18);
        console.log("      int256 %s and Fixed6 %s", i, f6);
        console.log("      int256 %s and Fixed18 %s", i, f18);
        console.log("      address %s and uint256 %s", a, u);
        console.log("      address %s and int256 %s", a, i);
        console.log("      address %s and address %s", a, a);
        console.log("      address %s and bool %s", a, b);
        console.log("      address %s and UFixed6 %s", a, uf6);
        console.log("      address %s and UFixed18 %s", a, uf18);
        console.log("      address %s and Fixed6 %s", a, f6);
        console.log("      address %s and Fixed18 %s", a, f18);
        console.log("      bool %s and uint256 %s", b, u);
        console.log("      bool %s and int256 %s", b, i);
        console.log("      bool %s and address %s", b, a);
        console.log("      bool %s and bool %s", b, b);
        console.log("      bool %s and UFixed6 %s", b, uf6);
        console.log("      bool %s and UFixed18 %s", b, uf18);
        console.log("      bool %s and Fixed6 %s", b, f6);
        console.log("      bool %s and Fixed18 %s", b, f18);
        console.log("      UFixed6 %s and uint256 %s", uf6, u);
        console.log("      UFixed6 %s and int256 %s", uf6, i);
        console.log("      UFixed6 %s and address %s", uf6, a);
        console.log("      UFixed6 %s and bool %s", uf6, b);
        console.log("      UFixed6 %s and UFixed6 %s", uf6, uf6);
        console.log("      UFixed6 %s and UFixed18 %s", uf6, uf18);
        console.log("      UFixed6 %s and Fixed6 %s", uf6, f6);
        console.log("      UFixed6 %s and Fixed18 %s", uf6, f18);
        console.log("      UFixed18 %s and uint256 %s", uf18, u);
        console.log("      UFixed18 %s and int256 %s", uf18, i);
        console.log("      UFixed18 %s and address %s", uf18, a);
        console.log("      UFixed18 %s and bool %s", uf18, b);
        console.log("      UFixed18 %s and UFixed6 %s", uf18, uf6);
        console.log("      UFixed18 %s and UFixed18 %s", uf18, uf18);
        console.log("      UFixed18 %s and Fixed6 %s", uf18, f6);
        console.log("      UFixed18 %s and Fixed18 %s", uf18, f18);
        console.log("      Fixed6 %s and uint256 %s", f6, u);
        console.log("      Fixed6 %s and int256 %s", f6, i);
        console.log("      Fixed6 %s and address %s", f6, a);
        console.log("      Fixed6 %s and bool %s", f6, b);
        console.log("      Fixed6 %s and UFixed6 %s", f6, uf6);
        console.log("      Fixed6 %s and UFixed18 %s", f6, uf18);
        console.log("      Fixed6 %s and Fixed6 %s", f6, f6);
        console.log("      Fixed6 %s and Fixed18 %s", f6, f18);
        console.log("      Fixed18 %s and uint256 %s", f18, u);
        console.log("      Fixed18 %s and int256 %s", f18, i);
        console.log("      Fixed18 %s and address %s", f18, a);
        console.log("      Fixed18 %s and bool %s", f18, b);
        console.log("      Fixed18 %s and UFixed6 %s", f18, uf6);
        console.log("      Fixed18 %s and UFixed18 %s", f18, uf18);
        console.log("      Fixed18 %s and Fixed6 %s", f18, f6);
        console.log("      Fixed18 %s and Fixed18 %s", f18, f18);
    }

    function test_formatThreeValues(
        uint256 u,
        int256 i,
        address a,
        bool b
    ) external pure {
        UFixed6 uf6 = UFixed6Lib.from(bound(u, 0, MAX_UFIXED6));
        UFixed18 uf18 = UFixed18Lib.from(bound(u, 0, MAX_UFIXED18));
        Fixed6 f6 = Fixed6Lib.from(bound(i, MIN_FIXED6, MAX_FIXED6));
        Fixed18 f18 = Fixed18Lib.from(bound(i, MIN_FIXED18, MAX_FIXED18));
        console.log("      uint256 %s, uint256 %s and uint256 %s", u, u, u);
        console.log("      uint256 %s, uint256 %s and int256 %s", u, u, i);
        console.log("      uint256 %s, uint256 %s and address %s", u, u, a);
        console.log("      uint256 %s, uint256 %s and bool %s", u, u, b);
        console.log("      uint256 %s, uint256 %s and UFixed6 %s", u, u, uf6);
        console.log("      uint256 %s, uint256 %s and UFixed18 %s", u, u, uf18);
        console.log("      uint256 %s, uint256 %s and Fixed6 %s", u, u, f6);
        console.log("      uint256 %s, uint256 %s and Fixed18 %s", u, u, f18);
        console.log("      uint256 %s, int256 %s and uint256 %s", u, i, u);
        console.log("      uint256 %s, int256 %s and int256 %s", u, i, i);
        console.log("      uint256 %s, int256 %s and address %s", u, i, a);
        console.log("      uint256 %s, int256 %s and bool %s", u, i, b);
        console.log("      uint256 %s, int256 %s and UFixed6 %s", u, i, uf6);
        console.log("      uint256 %s, int256 %s and UFixed18 %s", u, i, uf18);
        console.log("      uint256 %s, int256 %s and Fixed6 %s", u, i, f6);
        console.log("      uint256 %s, int256 %s and Fixed18 %s", u, i, f18);
        console.log("      uint256 %s, address %s and uint256 %s", u, a, u);
        console.log("      uint256 %s, address %s and int256 %s", u, a, i);
        console.log("      uint256 %s, address %s and address %s", u, a, a);
        console.log("      uint256 %s, address %s and bool %s", u, a, b);
        console.log("      uint256 %s, address %s and UFixed6 %s", u, a, uf6);
        console.log("      uint256 %s, address %s and UFixed18 %s", u, a, uf18);
        console.log("      uint256 %s, address %s and Fixed6 %s", u, a, f6);
        console.log("      uint256 %s, address %s and Fixed18 %s", u, a, f18);
        console.log("      uint256 %s, bool %s and uint256 %s", u, b, u);
        console.log("      uint256 %s, bool %s and int256 %s", u, b, i);
        console.log("      uint256 %s, bool %s and address %s", u, b, a);
        console.log("      uint256 %s, bool %s and bool %s", u, b, b);
        console.log("      uint256 %s, bool %s and UFixed6 %s", u, b, uf6);
        console.log("      uint256 %s, bool %s and UFixed18 %s", u, b, uf18);
        console.log("      uint256 %s, bool %s and Fixed6 %s", u, b, f6);
        console.log("      uint256 %s, bool %s and Fixed18 %s", u, b, f18);
        console.log("      uint256 %s, UFixed6 %s and uint256 %s", u, uf6, u);
        console.log("      uint256 %s, UFixed6 %s and int256 %s", u, uf6, i);
        console.log("      uint256 %s, UFixed6 %s and address %s", u, uf6, a);
        console.log("      uint256 %s, UFixed6 %s and bool %s", u, uf6, b);
        console.log("      uint256 %s, UFixed6 %s and UFixed6 %s", u, uf6, uf6);
        console.log("      uint256 %s, UFixed6 %s and UFixed18 %s", u, uf6, uf18);
        console.log("      uint256 %s, UFixed6 %s and Fixed6 %s", u, uf6, f6);
        console.log("      uint256 %s, UFixed6 %s and Fixed18 %s", u, uf6, f18);
        console.log("      uint256 %s, UFixed18 %s and uint256 %s", u, uf18, u);
        console.log("      uint256 %s, UFixed18 %s and int256 %s", u, uf18, i);
        console.log("      uint256 %s, UFixed18 %s and address %s", u, uf18, a);
        console.log("      uint256 %s, UFixed18 %s and bool %s", u, uf18, b);
        console.log("      uint256 %s, UFixed18 %s and UFixed6 %s", u, uf18, uf6);
        console.log("      uint256 %s, UFixed18 %s and UFixed18 %s", u, uf18, uf18);
        console.log("      uint256 %s, UFixed18 %s and Fixed6 %s", u, uf18, f6);
        console.log("      uint256 %s, UFixed18 %s and Fixed18 %s", u, uf18, f18);
        console.log("      uint256 %s, Fixed6 %s and uint256 %s", u, f6, u);
        console.log("      uint256 %s, Fixed6 %s and int256 %s", u, f6, i);
        console.log("      uint256 %s, Fixed6 %s and address %s", u, f6, a);
        console.log("      uint256 %s, Fixed6 %s and bool %s", u, f6, b);
        console.log("      uint256 %s, Fixed6 %s and UFixed6 %s", u, f6, uf6);
        console.log("      uint256 %s, Fixed6 %s and UFixed18 %s", u, f6, uf18);
        console.log("      uint256 %s, Fixed6 %s and Fixed6 %s", u, f6, f6);
        console.log("      uint256 %s, Fixed6 %s and Fixed18 %s", u, f6, f18);
        console.log("      uint256 %s, Fixed18 %s and uint256 %s", u, f18, u);
        console.log("      uint256 %s, Fixed18 %s and int256 %s", u, f18, i);
        console.log("      uint256 %s, Fixed18 %s and address %s", u, f18, a);
        console.log("      uint256 %s, Fixed18 %s and bool %s", u, f18, b);
        console.log("      uint256 %s, Fixed18 %s and UFixed6 %s", u, f18, uf6);
        console.log("      uint256 %s, Fixed18 %s and UFixed18 %s", u, f18, uf18);
        console.log("      uint256 %s, Fixed18 %s and Fixed6 %s", u, f18, f6);
        console.log("      uint256 %s, Fixed18 %s and Fixed18 %s", u, f18, f18);
        console.log("      int256 %s, uint256 %s and uint256 %s", i, u, u);
        console.log("      int256 %s, uint256 %s and int256 %s", i, u, i);
        console.log("      int256 %s, uint256 %s and address %s", i, u, a);
        console.log("      int256 %s, uint256 %s and bool %s", i, u, b);
        console.log("      int256 %s, uint256 %s and UFixed6 %s", i, u, uf6);
        console.log("      int256 %s, uint256 %s and UFixed18 %s", i, u, uf18);
        console.log("      int256 %s, uint256 %s and Fixed6 %s", i, u, f6);
        console.log("      int256 %s, uint256 %s and Fixed18 %s", i, u, f18);
        console.log("      int256 %s, int256 %s and uint256 %s", i, i, u);
        console.log("      int256 %s, int256 %s and int256 %s", i, i, i);
        console.log("      int256 %s, int256 %s and address %s", i, i, a);
        console.log("      int256 %s, int256 %s and bool %s", i, i, b);
        console.log("      int256 %s, int256 %s and UFixed6 %s", i, i, uf6);
        console.log("      int256 %s, int256 %s and UFixed18 %s", i, i, uf18);
        console.log("      int256 %s, int256 %s and Fixed6 %s", i, i, f6);
        console.log("      int256 %s, int256 %s and Fixed18 %s", i, i, f18);
        console.log("      int256 %s, address %s and uint256 %s", i, a, u);
        console.log("      int256 %s, address %s and int256 %s", i, a, i);
        console.log("      int256 %s, address %s and address %s", i, a, a);
        console.log("      int256 %s, address %s and bool %s", i, a, b);
        console.log("      int256 %s, address %s and UFixed6 %s", i, a, uf6);
        console.log("      int256 %s, address %s and UFixed18 %s", i, a, uf18);
        console.log("      int256 %s, address %s and Fixed6 %s", i, a, f6);
        console.log("      int256 %s, address %s and Fixed18 %s", i, a, f18);
        console.log("      int256 %s, bool %s and uint256 %s", i, b, u);
        console.log("      int256 %s, bool %s and int256 %s", i, b, i);
        console.log("      int256 %s, bool %s and address %s", i, b, a);
        console.log("      int256 %s, bool %s and bool %s", i, b, b);
        console.log("      int256 %s, bool %s and UFixed6 %s", i, b, uf6);
        console.log("      int256 %s, bool %s and UFixed18 %s", i, b, uf18);
        console.log("      int256 %s, bool %s and Fixed6 %s", i, b, f6);
        console.log("      int256 %s, bool %s and Fixed18 %s", i, b, f18);
        console.log("      int256 %s, UFixed6 %s and uint256 %s", i, uf6, u);
        console.log("      int256 %s, UFixed6 %s and int256 %s", i, uf6, i);
        console.log("      int256 %s, UFixed6 %s and address %s", i, uf6, a);
        console.log("      int256 %s, UFixed6 %s and bool %s", i, uf6, b);
        console.log("      int256 %s, UFixed6 %s and UFixed6 %s", i, uf6, uf6);
        console.log("      int256 %s, UFixed6 %s and UFixed18 %s", i, uf6, uf18);
        console.log("      int256 %s, UFixed6 %s and Fixed6 %s", i, uf6, f6);
        console.log("      int256 %s, UFixed6 %s and Fixed18 %s", i, uf6, f18);
        console.log("      int256 %s, UFixed18 %s and uint256 %s", i, uf18, u);
        console.log("      int256 %s, UFixed18 %s and int256 %s", i, uf18, i);
        console.log("      int256 %s, UFixed18 %s and address %s", i, uf18, a);
        console.log("      int256 %s, UFixed18 %s and bool %s", i, uf18, b);
        console.log("      int256 %s, UFixed18 %s and UFixed6 %s", i, uf18, uf6);
        console.log("      int256 %s, UFixed18 %s and UFixed18 %s", i, uf18, uf18);
        console.log("      int256 %s, UFixed18 %s and Fixed6 %s", i, uf18, f6);
        console.log("      int256 %s, UFixed18 %s and Fixed18 %s", i, uf18, f18);
        console.log("      int256 %s, Fixed6 %s and uint256 %s", i, f6, u);
        console.log("      int256 %s, Fixed6 %s and int256 %s", i, f6, i);
        console.log("      int256 %s, Fixed6 %s and address %s", i, f6, a);
        console.log("      int256 %s, Fixed6 %s and bool %s", i, f6, b);
        console.log("      int256 %s, Fixed6 %s and UFixed6 %s", i, f6, uf6);
        console.log("      int256 %s, Fixed6 %s and UFixed18 %s", i, f6, uf18);
        console.log("      int256 %s, Fixed6 %s and Fixed6 %s", i, f6, f6);
        console.log("      int256 %s, Fixed6 %s and Fixed18 %s", i, f6, f18);
        console.log("      int256 %s, Fixed18 %s and uint256 %s", i, f18, u);
        console.log("      int256 %s, Fixed18 %s and int256 %s", i, f18, i);
        console.log("      int256 %s, Fixed18 %s and address %s", i, f18, a);
        console.log("      int256 %s, Fixed18 %s and bool %s", i, f18, b);
        console.log("      int256 %s, Fixed18 %s and UFixed6 %s", i, f18, uf6);
        console.log("      int256 %s, Fixed18 %s and UFixed18 %s", i, f18, uf18);
        console.log("      int256 %s, Fixed18 %s and Fixed6 %s", i, f18, f6);
        console.log("      int256 %s, Fixed18 %s and Fixed18 %s", i, f18, f18);
        console.log("      address %s, uint256 %s and uint256 %s", a, u, u);
        console.log("      address %s, uint256 %s and int256 %s", a, u, i);
        console.log("      address %s, uint256 %s and address %s", a, u, a);
        console.log("      address %s, uint256 %s and bool %s", a, u, b);
        console.log("      address %s, uint256 %s and UFixed6 %s", a, u, uf6);
        console.log("      address %s, uint256 %s and UFixed18 %s", a, u, uf18);
        console.log("      address %s, uint256 %s and Fixed6 %s", a, u, f6);
        console.log("      address %s, uint256 %s and Fixed18 %s", a, u, f18);
        console.log("      address %s, int256 %s and uint256 %s", a, i, u);
        console.log("      address %s, int256 %s and int256 %s", a, i, i);
        console.log("      address %s, int256 %s and address %s", a, i, a);
        console.log("      address %s, int256 %s and bool %s", a, i, b);
        console.log("      address %s, int256 %s and UFixed6 %s", a, i, uf6);
        console.log("      address %s, int256 %s and UFixed18 %s", a, i, uf18);
        console.log("      address %s, int256 %s and Fixed6 %s", a, i, f6);
        console.log("      address %s, int256 %s and Fixed18 %s", a, i, f18);
        console.log("      address %s, address %s and uint256 %s", a, a, u);
        console.log("      address %s, address %s and int256 %s", a, a, i);
        console.log("      address %s, address %s and address %s", a, a, a);
        console.log("      address %s, address %s and bool %s", a, a, b);
        console.log("      address %s, address %s and UFixed6 %s", a, a, uf6);
        console.log("      address %s, address %s and UFixed18 %s", a, a, uf18);
        console.log("      address %s, address %s and Fixed6 %s", a, a, f6);
        console.log("      address %s, address %s and Fixed18 %s", a, a, f18);
        console.log("      address %s, bool %s and uint256 %s", a, b, u);
        console.log("      address %s, bool %s and int256 %s", a, b, i);
        console.log("      address %s, bool %s and address %s", a, b, a);
        console.log("      address %s, bool %s and bool %s", a, b, b);
        console.log("      address %s, bool %s and UFixed6 %s", a, b, uf6);
        console.log("      address %s, bool %s and UFixed18 %s", a, b, uf18);
        console.log("      address %s, bool %s and Fixed6 %s", a, b, f6);
        console.log("      address %s, bool %s and Fixed18 %s", a, b, f18);
        console.log("      address %s, UFixed6 %s and uint256 %s", a, uf6, u);
        console.log("      address %s, UFixed6 %s and int256 %s", a, uf6, i);
        console.log("      address %s, UFixed6 %s and address %s", a, uf6, a);
        console.log("      address %s, UFixed6 %s and bool %s", a, uf6, b);
        console.log("      address %s, UFixed6 %s and UFixed6 %s", a, uf6, uf6);
        console.log("      address %s, UFixed6 %s and UFixed18 %s", a, uf6, uf18);
        console.log("      address %s, UFixed6 %s and Fixed6 %s", a, uf6, f6);
        console.log("      address %s, UFixed6 %s and Fixed18 %s", a, uf6, f18);
        console.log("      address %s, UFixed18 %s and uint256 %s", a, uf18, u);
        console.log("      address %s, UFixed18 %s and int256 %s", a, uf18, i);
        console.log("      address %s, UFixed18 %s and address %s", a, uf18, a);
        console.log("      address %s, UFixed18 %s and bool %s", a, uf18, b);
        console.log("      address %s, UFixed18 %s and UFixed6 %s", a, uf18, uf6);
        console.log("      address %s, UFixed18 %s and UFixed18 %s", a, uf18, uf18);
        console.log("      address %s, UFixed18 %s and Fixed6 %s", a, uf18, f6);
        console.log("      address %s, UFixed18 %s and Fixed18 %s", a, uf18, f18);
        console.log("      address %s, Fixed6 %s and uint256 %s", a, f6, u);
        console.log("      address %s, Fixed6 %s and int256 %s", a, f6, i);
        console.log("      address %s, Fixed6 %s and address %s", a, f6, a);
        console.log("      address %s, Fixed6 %s and bool %s", a, f6, b);
        console.log("      address %s, Fixed6 %s and UFixed6 %s", a, f6, uf6);
        console.log("      address %s, Fixed6 %s and UFixed18 %s", a, f6, uf18);
        console.log("      address %s, Fixed6 %s and Fixed6 %s", a, f6, f6);
        console.log("      address %s, Fixed6 %s and Fixed18 %s", a, f6, f18);
        console.log("      address %s, Fixed18 %s and uint256 %s", a, f18, u);
        console.log("      address %s, Fixed18 %s and int256 %s", a, f18, i);
        console.log("      address %s, Fixed18 %s and address %s", a, f18, a);
        console.log("      address %s, Fixed18 %s and bool %s", a, f18, b);
        console.log("      address %s, Fixed18 %s and UFixed6 %s", a, f18, uf6);
        console.log("      address %s, Fixed18 %s and UFixed18 %s", a, f18, uf18);
        console.log("      address %s, Fixed18 %s and Fixed6 %s", a, f18, f6);
        console.log("      address %s, Fixed18 %s and Fixed18 %s", a, f18, f18);
        console.log("      bool %s, uint256 %s and uint256 %s", b, u, u);
        console.log("      bool %s, uint256 %s and int256 %s", b, u, i);
        console.log("      bool %s, uint256 %s and address %s", b, u, a);
        console.log("      bool %s, uint256 %s and bool %s", b, u, b);
        console.log("      bool %s, uint256 %s and UFixed6 %s", b, u, uf6);
        console.log("      bool %s, uint256 %s and UFixed18 %s", b, u, uf18);
        console.log("      bool %s, uint256 %s and Fixed6 %s", b, u, f6);
        console.log("      bool %s, uint256 %s and Fixed18 %s", b, u, f18);
        console.log("      bool %s, int256 %s and uint256 %s", b, i, u);
        console.log("      bool %s, int256 %s and int256 %s", b, i, i);
        console.log("      bool %s, int256 %s and address %s", b, i, a);
        console.log("      bool %s, int256 %s and bool %s", b, i, b);
        console.log("      bool %s, int256 %s and UFixed6 %s", b, i, uf6);
        console.log("      bool %s, int256 %s and UFixed18 %s", b, i, uf18);
        console.log("      bool %s, int256 %s and Fixed6 %s", b, i, f6);
        console.log("      bool %s, int256 %s and Fixed18 %s", b, i, f18);
        console.log("      bool %s, address %s and uint256 %s", b, a, u);
        console.log("      bool %s, address %s and int256 %s", b, a, i);
        console.log("      bool %s, address %s and address %s", b, a, a);
        console.log("      bool %s, address %s and bool %s", b, a, b);
        console.log("      bool %s, address %s and UFixed6 %s", b, a, uf6);
        console.log("      bool %s, address %s and UFixed18 %s", b, a, uf18);
        console.log("      bool %s, address %s and Fixed6 %s", b, a, f6);
        console.log("      bool %s, address %s and Fixed18 %s", b, a, f18);
        console.log("      bool %s, bool %s and uint256 %s", b, b, u);
        console.log("      bool %s, bool %s and int256 %s", b, b, i);
        console.log("      bool %s, bool %s and address %s", b, b, a);
        console.log("      bool %s, bool %s and bool %s", b, b, b);
        console.log("      bool %s, bool %s and UFixed6 %s", b, b, uf6);
        console.log("      bool %s, bool %s and UFixed18 %s", b, b, uf18);
        console.log("      bool %s, bool %s and Fixed6 %s", b, b, f6);
        console.log("      bool %s, bool %s and Fixed18 %s", b, b, f18);
        console.log("      bool %s, UFixed6 %s and uint256 %s", b, uf6, u);
        console.log("      bool %s, UFixed6 %s and int256 %s", b, uf6, i);
        console.log("      bool %s, UFixed6 %s and address %s", b, uf6, a);
        console.log("      bool %s, UFixed6 %s and bool %s", b, uf6, b);
        console.log("      bool %s, UFixed6 %s and UFixed6 %s", b, uf6, uf6);
        console.log("      bool %s, UFixed6 %s and UFixed18 %s", b, uf6, uf18);
        console.log("      bool %s, UFixed6 %s and Fixed6 %s", b, uf6, f6);
        console.log("      bool %s, UFixed6 %s and Fixed18 %s", b, uf6, f18);
        console.log("      bool %s, UFixed18 %s and uint256 %s", b, uf18, u);
        console.log("      bool %s, UFixed18 %s and int256 %s", b, uf18, i);
        console.log("      bool %s, UFixed18 %s and address %s", b, uf18, a);
        console.log("      bool %s, UFixed18 %s and bool %s", b, uf18, b);
        console.log("      bool %s, UFixed18 %s and UFixed6 %s", b, uf18, uf6);
        console.log("      bool %s, UFixed18 %s and UFixed18 %s", b, uf18, uf18);
        console.log("      bool %s, UFixed18 %s and Fixed6 %s", b, uf18, f6);
        console.log("      bool %s, UFixed18 %s and Fixed18 %s", b, uf18, f18);
        console.log("      bool %s, Fixed6 %s and uint256 %s", b, f6, u);
        console.log("      bool %s, Fixed6 %s and int256 %s", b, f6, i);
        console.log("      bool %s, Fixed6 %s and address %s", b, f6, a);
        console.log("      bool %s, Fixed6 %s and bool %s", b, f6, b);
        console.log("      bool %s, Fixed6 %s and UFixed6 %s", b, f6, uf6);
        console.log("      bool %s, Fixed6 %s and UFixed18 %s", b, f6, uf18);
        console.log("      bool %s, Fixed6 %s and Fixed6 %s", b, f6, f6);
        console.log("      bool %s, Fixed6 %s and Fixed18 %s", b, f6, f18);
        console.log("      bool %s, Fixed18 %s and uint256 %s", b, f18, u);
        console.log("      bool %s, Fixed18 %s and int256 %s", b, f18, i);
        console.log("      bool %s, Fixed18 %s and address %s", b, f18, a);
        console.log("      bool %s, Fixed18 %s and bool %s", b, f18, b);
        console.log("      bool %s, Fixed18 %s and UFixed6 %s", b, f18, uf6);
        console.log("      bool %s, Fixed18 %s and UFixed18 %s", b, f18, uf18);
        console.log("      bool %s, Fixed18 %s and Fixed6 %s", b, f18, f6);
        console.log("      bool %s, Fixed18 %s and Fixed18 %s", b, f18, f18);
        console.log("      UFixed6 %s, uint256 %s and uint256 %s", uf6, u, u);
        console.log("      UFixed6 %s, uint256 %s and int256 %s", uf6, u, i);
        console.log("      UFixed6 %s, uint256 %s and address %s", uf6, u, a);
        console.log("      UFixed6 %s, uint256 %s and bool %s", uf6, u, b);
        console.log("      UFixed6 %s, uint256 %s and UFixed6 %s", uf6, u, uf6);
        console.log("      UFixed6 %s, uint256 %s and UFixed18 %s", uf6, u, uf18);
        console.log("      UFixed6 %s, uint256 %s and Fixed6 %s", uf6, u, f6);
        console.log("      UFixed6 %s, uint256 %s and Fixed18 %s", uf6, u, f18);
        console.log("      UFixed6 %s, int256 %s and uint256 %s", uf6, i, u);
        console.log("      UFixed6 %s, int256 %s and int256 %s", uf6, i, i);
        console.log("      UFixed6 %s, int256 %s and address %s", uf6, i, a);
        console.log("      UFixed6 %s, int256 %s and bool %s", uf6, i, b);
        console.log("      UFixed6 %s, int256 %s and UFixed6 %s", uf6, i, uf6);
        console.log("      UFixed6 %s, int256 %s and UFixed18 %s", uf6, i, uf18);
        console.log("      UFixed6 %s, int256 %s and Fixed6 %s", uf6, i, f6);
        console.log("      UFixed6 %s, int256 %s and Fixed18 %s", uf6, i, f18);
        console.log("      UFixed6 %s, address %s and uint256 %s", uf6, a, u);
        console.log("      UFixed6 %s, address %s and int256 %s", uf6, a, i);
        console.log("      UFixed6 %s, address %s and address %s", uf6, a, a);
        console.log("      UFixed6 %s, address %s and bool %s", uf6, a, b);
        console.log("      UFixed6 %s, address %s and UFixed6 %s", uf6, a, uf6);
        console.log("      UFixed6 %s, address %s and UFixed18 %s", uf6, a, uf18);
        console.log("      UFixed6 %s, address %s and Fixed6 %s", uf6, a, f6);
        console.log("      UFixed6 %s, address %s and Fixed18 %s", uf6, a, f18);
        console.log("      UFixed6 %s, bool %s and uint256 %s", uf6, b, u);
        console.log("      UFixed6 %s, bool %s and int256 %s", uf6, b, i);
        console.log("      UFixed6 %s, bool %s and address %s", uf6, b, a);
        console.log("      UFixed6 %s, bool %s and bool %s", uf6, b, b);
        console.log("      UFixed6 %s, bool %s and UFixed6 %s", uf6, b, uf6);
        console.log("      UFixed6 %s, bool %s and UFixed18 %s", uf6, b, uf18);
        console.log("      UFixed6 %s, bool %s and Fixed6 %s", uf6, b, f6);
        console.log("      UFixed6 %s, bool %s and Fixed18 %s", uf6, b, f18);
        console.log("      UFixed6 %s, UFixed6 %s and uint256 %s", uf6, uf6, u);
        console.log("      UFixed6 %s, UFixed6 %s and int256 %s", uf6, uf6, i);
        console.log("      UFixed6 %s, UFixed6 %s and address %s", uf6, uf6, a);
        console.log("      UFixed6 %s, UFixed6 %s and bool %s", uf6, uf6, b);
        console.log("      UFixed6 %s, UFixed6 %s and UFixed6 %s", uf6, uf6, uf6);
        console.log("      UFixed6 %s, UFixed6 %s and UFixed18 %s", uf6, uf6, uf18);
        console.log("      UFixed6 %s, UFixed6 %s and Fixed6 %s", uf6, uf6, f6);
        console.log("      UFixed6 %s, UFixed6 %s and Fixed18 %s", uf6, uf6, f18);
        console.log("      UFixed6 %s, UFixed18 %s and uint256 %s", uf6, uf18, u);
        console.log("      UFixed6 %s, UFixed18 %s and int256 %s", uf6, uf18, i);
        console.log("      UFixed6 %s, UFixed18 %s and address %s", uf6, uf18, a);
        console.log("      UFixed6 %s, UFixed18 %s and bool %s", uf6, uf18, b);
        console.log("      UFixed6 %s, UFixed18 %s and UFixed6 %s", uf6, uf18, uf6);
        console.log("      UFixed6 %s, UFixed18 %s and UFixed18 %s", uf6, uf18, uf18);
        console.log("      UFixed6 %s, UFixed18 %s and Fixed6 %s", uf6, uf18, f6);
        console.log("      UFixed6 %s, UFixed18 %s and Fixed18 %s", uf6, uf18, f18);
        console.log("      UFixed6 %s, Fixed6 %s and uint256 %s", uf6, f6, u);
        console.log("      UFixed6 %s, Fixed6 %s and int256 %s", uf6, f6, i);
        console.log("      UFixed6 %s, Fixed6 %s and address %s", uf6, f6, a);
        console.log("      UFixed6 %s, Fixed6 %s and bool %s", uf6, f6, b);
        console.log("      UFixed6 %s, Fixed6 %s and UFixed6 %s", uf6, f6, uf6);
        console.log("      UFixed6 %s, Fixed6 %s and UFixed18 %s", uf6, f6, uf18);
        console.log("      UFixed6 %s, Fixed6 %s and Fixed6 %s", uf6, f6, f6);
        console.log("      UFixed6 %s, Fixed6 %s and Fixed18 %s", uf6, f6, f18);
        console.log("      UFixed6 %s, Fixed18 %s and uint256 %s", uf6, f18, u);
        console.log("      UFixed6 %s, Fixed18 %s and int256 %s", uf6, f18, i);
        console.log("      UFixed6 %s, Fixed18 %s and address %s", uf6, f18, a);
        console.log("      UFixed6 %s, Fixed18 %s and bool %s", uf6, f18, b);
        console.log("      UFixed6 %s, Fixed18 %s and UFixed6 %s", uf6, f18, uf6);
        console.log("      UFixed6 %s, Fixed18 %s and UFixed18 %s", uf6, f18, uf18);
        console.log("      UFixed6 %s, Fixed18 %s and Fixed6 %s", uf6, f18, f6);
        console.log("      UFixed6 %s, Fixed18 %s and Fixed18 %s", uf6, f18, f18);
        console.log("      UFixed18 %s, uint256 %s and uint256 %s", uf18, u, u);
        console.log("      UFixed18 %s, uint256 %s and int256 %s", uf18, u, i);
        console.log("      UFixed18 %s, uint256 %s and address %s", uf18, u, a);
        console.log("      UFixed18 %s, uint256 %s and bool %s", uf18, u, b);
        console.log("      UFixed18 %s, uint256 %s and UFixed6 %s", uf18, u, uf6);
        console.log("      UFixed18 %s, uint256 %s and UFixed18 %s", uf18, u, uf18);
        console.log("      UFixed18 %s, uint256 %s and Fixed6 %s", uf18, u, f6);
        console.log("      UFixed18 %s, uint256 %s and Fixed18 %s", uf18, u, f18);
        console.log("      UFixed18 %s, int256 %s and uint256 %s", uf18, i, u);
        console.log("      UFixed18 %s, int256 %s and int256 %s", uf18, i, i);
        console.log("      UFixed18 %s, int256 %s and address %s", uf18, i, a);
        console.log("      UFixed18 %s, int256 %s and bool %s", uf18, i, b);
        console.log("      UFixed18 %s, int256 %s and UFixed6 %s", uf18, i, uf6);
        console.log("      UFixed18 %s, int256 %s and UFixed18 %s", uf18, i, uf18);
        console.log("      UFixed18 %s, int256 %s and Fixed6 %s", uf18, i, f6);
        console.log("      UFixed18 %s, int256 %s and Fixed18 %s", uf18, i, f18);
        console.log("      UFixed18 %s, address %s and uint256 %s", uf18, a, u);
        console.log("      UFixed18 %s, address %s and int256 %s", uf18, a, i);
        console.log("      UFixed18 %s, address %s and address %s", uf18, a, a);
        console.log("      UFixed18 %s, address %s and bool %s", uf18, a, b);
        console.log("      UFixed18 %s, address %s and UFixed6 %s", uf18, a, uf6);
        console.log("      UFixed18 %s, address %s and UFixed18 %s", uf18, a, uf18);
        console.log("      UFixed18 %s, address %s and Fixed6 %s", uf18, a, f6);
        console.log("      UFixed18 %s, address %s and Fixed18 %s", uf18, a, f18);
        console.log("      UFixed18 %s, bool %s and uint256 %s", uf18, b, u);
        console.log("      UFixed18 %s, bool %s and int256 %s", uf18, b, i);
        console.log("      UFixed18 %s, bool %s and address %s", uf18, b, a);
        console.log("      UFixed18 %s, bool %s and bool %s", uf18, b, b);
        console.log("      UFixed18 %s, bool %s and UFixed6 %s", uf18, b, uf6);
        console.log("      UFixed18 %s, bool %s and UFixed18 %s", uf18, b, uf18);
        console.log("      UFixed18 %s, bool %s and Fixed6 %s", uf18, b, f6);
        console.log("      UFixed18 %s, bool %s and Fixed18 %s", uf18, b, f18);
        console.log("      UFixed18 %s, UFixed6 %s and uint256 %s", uf18, uf6, u);
        console.log("      UFixed18 %s, UFixed6 %s and int256 %s", uf18, uf6, i);
        console.log("      UFixed18 %s, UFixed6 %s and address %s", uf18, uf6, a);
        console.log("      UFixed18 %s, UFixed6 %s and bool %s", uf18, uf6, b);
        console.log("      UFixed18 %s, UFixed6 %s and UFixed6 %s", uf18, uf6, uf6);
        console.log("      UFixed18 %s, UFixed6 %s and UFixed18 %s", uf18, uf6, uf18);
        console.log("      UFixed18 %s, UFixed6 %s and Fixed6 %s", uf18, uf6, f6);
        console.log("      UFixed18 %s, UFixed6 %s and Fixed18 %s", uf18, uf6, f18);
        console.log("      UFixed18 %s, UFixed18 %s and uint256 %s", uf18, uf18, u);
        console.log("      UFixed18 %s, UFixed18 %s and int256 %s", uf18, uf18, i);
        console.log("      UFixed18 %s, UFixed18 %s and address %s", uf18, uf18, a);
        console.log("      UFixed18 %s, UFixed18 %s and bool %s", uf18, uf18, b);
        console.log("      UFixed18 %s, UFixed18 %s and UFixed6 %s", uf18, uf18, uf6);
        console.log("      UFixed18 %s, UFixed18 %s and UFixed18 %s", uf18, uf18, uf18);
        console.log("      UFixed18 %s, UFixed18 %s and Fixed6 %s", uf18, uf18, f6);
        console.log("      UFixed18 %s, UFixed18 %s and Fixed18 %s", uf18, uf18, f18);
        console.log("      UFixed18 %s, Fixed6 %s and uint256 %s", uf18, f6, u);
        console.log("      UFixed18 %s, Fixed6 %s and int256 %s", uf18, f6, i);
        console.log("      UFixed18 %s, Fixed6 %s and address %s", uf18, f6, a);
        console.log("      UFixed18 %s, Fixed6 %s and bool %s", uf18, f6, b);
        console.log("      UFixed18 %s, Fixed6 %s and UFixed6 %s", uf18, f6, uf6);
        console.log("      UFixed18 %s, Fixed6 %s and UFixed18 %s", uf18, f6, uf18);
        console.log("      UFixed18 %s, Fixed6 %s and Fixed6 %s", uf18, f6, f6);
        console.log("      UFixed18 %s, Fixed6 %s and Fixed18 %s", uf18, f6, f18);
        console.log("      UFixed18 %s, Fixed18 %s and uint256 %s", uf18, f18, u);
        console.log("      UFixed18 %s, Fixed18 %s and int256 %s", uf18, f18, i);
        console.log("      UFixed18 %s, Fixed18 %s and address %s", uf18, f18, a);
        console.log("      UFixed18 %s, Fixed18 %s and bool %s", uf18, f18, b);
        console.log("      UFixed18 %s, Fixed18 %s and UFixed6 %s", uf18, f18, uf6);
        console.log("      UFixed18 %s, Fixed18 %s and UFixed18 %s", uf18, f18, uf18);
        console.log("      UFixed18 %s, Fixed18 %s and Fixed6 %s", uf18, f18, f6);
        console.log("      UFixed18 %s, Fixed18 %s and Fixed18 %s", uf18, f18, f18);
        console.log("      Fixed6 %s, uint256 %s and uint256 %s", f6, u, u);
        console.log("      Fixed6 %s, uint256 %s and int256 %s", f6, u, i);
        console.log("      Fixed6 %s, uint256 %s and address %s", f6, u, a);
        console.log("      Fixed6 %s, uint256 %s and bool %s", f6, u, b);
        console.log("      Fixed6 %s, uint256 %s and UFixed6 %s", f6, u, uf6);
        console.log("      Fixed6 %s, uint256 %s and UFixed18 %s", f6, u, uf18);
        console.log("      Fixed6 %s, uint256 %s and Fixed6 %s", f6, u, f6);
        console.log("      Fixed6 %s, uint256 %s and Fixed18 %s", f6, u, f18);
        console.log("      Fixed6 %s, int256 %s and uint256 %s", f6, i, u);
        console.log("      Fixed6 %s, int256 %s and int256 %s", f6, i, i);
        console.log("      Fixed6 %s, int256 %s and address %s", f6, i, a);
        console.log("      Fixed6 %s, int256 %s and bool %s", f6, i, b);
        console.log("      Fixed6 %s, int256 %s and UFixed6 %s", f6, i, uf6);
        console.log("      Fixed6 %s, int256 %s and UFixed18 %s", f6, i, uf18);
        console.log("      Fixed6 %s, int256 %s and Fixed6 %s", f6, i, f6);
        console.log("      Fixed6 %s, int256 %s and Fixed18 %s", f6, i, f18);
        console.log("      Fixed6 %s, address %s and uint256 %s", f6, a, u);
        console.log("      Fixed6 %s, address %s and int256 %s", f6, a, i);
        console.log("      Fixed6 %s, address %s and address %s", f6, a, a);
        console.log("      Fixed6 %s, address %s and bool %s", f6, a, b);
        console.log("      Fixed6 %s, address %s and UFixed6 %s", f6, a, uf6);
        console.log("      Fixed6 %s, address %s and UFixed18 %s", f6, a, uf18);
        console.log("      Fixed6 %s, address %s and Fixed6 %s", f6, a, f6);
        console.log("      Fixed6 %s, address %s and Fixed18 %s", f6, a, f18);
        console.log("      Fixed6 %s, bool %s and uint256 %s", f6, b, u);
        console.log("      Fixed6 %s, bool %s and int256 %s", f6, b, i);
        console.log("      Fixed6 %s, bool %s and address %s", f6, b, a);
        console.log("      Fixed6 %s, bool %s and bool %s", f6, b, b);
        console.log("      Fixed6 %s, bool %s and UFixed6 %s", f6, b, uf6);
        console.log("      Fixed6 %s, bool %s and UFixed18 %s", f6, b, uf18);
        console.log("      Fixed6 %s, bool %s and Fixed6 %s", f6, b, f6);
        console.log("      Fixed6 %s, bool %s and Fixed18 %s", f6, b, f18);
        console.log("      Fixed6 %s, UFixed6 %s and uint256 %s", f6, uf6, u);
        console.log("      Fixed6 %s, UFixed6 %s and int256 %s", f6, uf6, i);
        console.log("      Fixed6 %s, UFixed6 %s and address %s", f6, uf6, a);
        console.log("      Fixed6 %s, UFixed6 %s and bool %s", f6, uf6, b);
        console.log("      Fixed6 %s, UFixed6 %s and UFixed6 %s", f6, uf6, uf6);
        console.log("      Fixed6 %s, UFixed6 %s and UFixed18 %s", f6, uf6, uf18);
        console.log("      Fixed6 %s, UFixed6 %s and Fixed6 %s", f6, uf6, f6);
        console.log("      Fixed6 %s, UFixed6 %s and Fixed18 %s", f6, uf6, f18);
        console.log("      Fixed6 %s, UFixed18 %s and uint256 %s", f6, uf18, u);
        console.log("      Fixed6 %s, UFixed18 %s and int256 %s", f6, uf18, i);
        console.log("      Fixed6 %s, UFixed18 %s and address %s", f6, uf18, a);
        console.log("      Fixed6 %s, UFixed18 %s and bool %s", f6, uf18, b);
        console.log("      Fixed6 %s, UFixed18 %s and UFixed6 %s", f6, uf18, uf6);
        console.log("      Fixed6 %s, UFixed18 %s and UFixed18 %s", f6, uf18, uf18);
        console.log("      Fixed6 %s, UFixed18 %s and Fixed6 %s", f6, uf18, f6);
        console.log("      Fixed6 %s, UFixed18 %s and Fixed18 %s", f6, uf18, f18);
        console.log("      Fixed6 %s, Fixed6 %s and uint256 %s", f6, f6, u);
        console.log("      Fixed6 %s, Fixed6 %s and int256 %s", f6, f6, i);
        console.log("      Fixed6 %s, Fixed6 %s and address %s", f6, f6, a);
        console.log("      Fixed6 %s, Fixed6 %s and bool %s", f6, f6, b);
        console.log("      Fixed6 %s, Fixed6 %s and UFixed6 %s", f6, f6, uf6);
        console.log("      Fixed6 %s, Fixed6 %s and UFixed18 %s", f6, f6, uf18);
        console.log("      Fixed6 %s, Fixed6 %s and Fixed6 %s", f6, f6, f6);
        console.log("      Fixed6 %s, Fixed6 %s and Fixed18 %s", f6, f6, f18);
        console.log("      Fixed6 %s, Fixed18 %s and uint256 %s", f6, f18, u);
        console.log("      Fixed6 %s, Fixed18 %s and int256 %s", f6, f18, i);
        console.log("      Fixed6 %s, Fixed18 %s and address %s", f6, f18, a);
        console.log("      Fixed6 %s, Fixed18 %s and bool %s", f6, f18, b);
        console.log("      Fixed6 %s, Fixed18 %s and UFixed6 %s", f6, f18, uf6);
        console.log("      Fixed6 %s, Fixed18 %s and UFixed18 %s", f6, f18, uf18);
        console.log("      Fixed6 %s, Fixed18 %s and Fixed6 %s", f6, f18, f6);
        console.log("      Fixed6 %s, Fixed18 %s and Fixed18 %s", f6, f18, f18);
        console.log("      Fixed18 %s, uint256 %s and uint256 %s", f18, u, u);
        console.log("      Fixed18 %s, uint256 %s and int256 %s", f18, u, i);
        console.log("      Fixed18 %s, uint256 %s and address %s", f18, u, a);
        console.log("      Fixed18 %s, uint256 %s and bool %s", f18, u, b);
        console.log("      Fixed18 %s, uint256 %s and UFixed6 %s", f18, u, uf6);
        console.log("      Fixed18 %s, uint256 %s and UFixed18 %s", f18, u, uf18);
        console.log("      Fixed18 %s, uint256 %s and Fixed6 %s", f18, u, f6);
        console.log("      Fixed18 %s, uint256 %s and Fixed18 %s", f18, u, f18);
        console.log("      Fixed18 %s, int256 %s and uint256 %s", f18, i, u);
        console.log("      Fixed18 %s, int256 %s and int256 %s", f18, i, i);
        console.log("      Fixed18 %s, int256 %s and address %s", f18, i, a);
        console.log("      Fixed18 %s, int256 %s and bool %s", f18, i, b);
        console.log("      Fixed18 %s, int256 %s and UFixed6 %s", f18, i, uf6);
        console.log("      Fixed18 %s, int256 %s and UFixed18 %s", f18, i, uf18);
        console.log("      Fixed18 %s, int256 %s and Fixed6 %s", f18, i, f6);
        console.log("      Fixed18 %s, int256 %s and Fixed18 %s", f18, i, f18);
        console.log("      Fixed18 %s, address %s and uint256 %s", f18, a, u);
        console.log("      Fixed18 %s, address %s and int256 %s", f18, a, i);
        console.log("      Fixed18 %s, address %s and address %s", f18, a, a);
        console.log("      Fixed18 %s, address %s and bool %s", f18, a, b);
        console.log("      Fixed18 %s, address %s and UFixed6 %s", f18, a, uf6);
        console.log("      Fixed18 %s, address %s and UFixed18 %s", f18, a, uf18);
        console.log("      Fixed18 %s, address %s and Fixed6 %s", f18, a, f6);
        console.log("      Fixed18 %s, address %s and Fixed18 %s", f18, a, f18);
        console.log("      Fixed18 %s, bool %s and uint256 %s", f18, b, u);
        console.log("      Fixed18 %s, bool %s and int256 %s", f18, b, i);
        console.log("      Fixed18 %s, bool %s and address %s", f18, b, a);
        console.log("      Fixed18 %s, bool %s and bool %s", f18, b, b);
        console.log("      Fixed18 %s, bool %s and UFixed6 %s", f18, b, uf6);
        console.log("      Fixed18 %s, bool %s and UFixed18 %s", f18, b, uf18);
        console.log("      Fixed18 %s, bool %s and Fixed6 %s", f18, b, f6);
        console.log("      Fixed18 %s, bool %s and Fixed18 %s", f18, b, f18);
        console.log("      Fixed18 %s, UFixed6 %s and uint256 %s", f18, uf6, u);
        console.log("      Fixed18 %s, UFixed6 %s and int256 %s", f18, uf6, i);
        console.log("      Fixed18 %s, UFixed6 %s and address %s", f18, uf6, a);
        console.log("      Fixed18 %s, UFixed6 %s and bool %s", f18, uf6, b);
        console.log("      Fixed18 %s, UFixed6 %s and UFixed6 %s", f18, uf6, uf6);
        console.log("      Fixed18 %s, UFixed6 %s and UFixed18 %s", f18, uf6, uf18);
        console.log("      Fixed18 %s, UFixed6 %s and Fixed6 %s", f18, uf6, f6);
        console.log("      Fixed18 %s, UFixed6 %s and Fixed18 %s", f18, uf6, f18);
        console.log("      Fixed18 %s, UFixed18 %s and uint256 %s", f18, uf18, u);
        console.log("      Fixed18 %s, UFixed18 %s and int256 %s", f18, uf18, i);
        console.log("      Fixed18 %s, UFixed18 %s and address %s", f18, uf18, a);
        console.log("      Fixed18 %s, UFixed18 %s and bool %s", f18, uf18, b);
        console.log("      Fixed18 %s, UFixed18 %s and UFixed6 %s", f18, uf18, uf6);
        console.log("      Fixed18 %s, UFixed18 %s and UFixed18 %s", f18, uf18, uf18);
        console.log("      Fixed18 %s, UFixed18 %s and Fixed6 %s", f18, uf18, f6);
        console.log("      Fixed18 %s, UFixed18 %s and Fixed18 %s", f18, uf18, f18);
        console.log("      Fixed18 %s, Fixed6 %s and uint256 %s", f18, f6, u);
        console.log("      Fixed18 %s, Fixed6 %s and int256 %s", f18, f6, i);
        console.log("      Fixed18 %s, Fixed6 %s and address %s", f18, f6, a);
        console.log("      Fixed18 %s, Fixed6 %s and bool %s", f18, f6, b);
        console.log("      Fixed18 %s, Fixed6 %s and UFixed6 %s", f18, f6, uf6);
        console.log("      Fixed18 %s, Fixed6 %s and UFixed18 %s", f18, f6, uf18);
        console.log("      Fixed18 %s, Fixed6 %s and Fixed6 %s", f18, f6, f6);
        console.log("      Fixed18 %s, Fixed6 %s and Fixed18 %s", f18, f6, f18);
        console.log("      Fixed18 %s, Fixed18 %s and uint256 %s", f18, f18, u);
        console.log("      Fixed18 %s, Fixed18 %s and int256 %s", f18, f18, i);
        console.log("      Fixed18 %s, Fixed18 %s and address %s", f18, f18, a);
        console.log("      Fixed18 %s, Fixed18 %s and bool %s", f18, f18, b);
        console.log("      Fixed18 %s, Fixed18 %s and UFixed6 %s", f18, f18, uf6);
        console.log("      Fixed18 %s, Fixed18 %s and UFixed18 %s", f18, f18, uf18);
        console.log("      Fixed18 %s, Fixed18 %s and Fixed6 %s", f18, f18, f6);
        console.log("      Fixed18 %s, Fixed18 %s and Fixed18 %s", f18, f18, f18);
    }
}
// solhint-enable no-console